config/routes.rb
Rails.application.routes.draw do
  devise_for :users,controllers: {
    registrations: 'users/registrations'
  }

  resources :posts
  resources :users
  resources :likes
  resources :comments
  resources :follows do 
    collection do 
      post "change"
    end
  end
  root to:"users#index"
  delete "/likes", to:"likes#destroy"
  post "/posts/likes/:id", to:"posts#add_like"
  delete "/posts/likes/:id", to:"posts#delete_like"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :body, presence:true
  has_many :likes
  has_many :likers, through: :likes, class_name: :User
  has_many :comments
  has_many :commenters, through: :comments, class_name: :User
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  def index
    all_post=Post.all
    @posts=all_post.filter do |post|
      current_user.followings.include?(post.user) && current_user.following.where(followed:post.user).take.status=='accepted' || post.user==current_user
    end
  end
  def show
    @post=Post.find(params[:id])
  end
  def new
    @post=Post.new
  end
  def create
    @post=current_user.posts.build(post_params)
    if @post.save
      redirect_to @post
    else
      render :new, status: :unprocessable_entity
    end
  end
  def add_like
    current_user.likes.create(post:Post.find(params[:id]))
    redirect_to Post.find(params[:id])
  end
  def delete_like
    current_user.likes.where(post:Post.find(params[:id])).destroy_all
    redirect_to Post.find(params[:id])
  end
 private
 def post_params
   params.expect(post:[:body])
 end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/index.html.erb
<%=link_to "Sign out",destroy_user_session_path, data:{"turbo-method": :delete}%>
<%=link_to "Users",users_path%>

<h1>Posts</h1>
<ul>
<%@posts.each do |post|%>
<li><%=link_to post.body,post%></li>
<%end%>
</ul>
<%=link_to "Create Post", new_post_path%>

app/views/posts/new.html.erb
<%=form_with model: @post do |form|%>
  <%=form.label :body, "Body"%>
  <%=form.text_field :body%>
  <%=form.submit%>
<%end%>

app/views/posts/show.html.erb
<%=link_to "Sign out",destroy_user_session_path, data:{"turbo-method": :delete}%>
<%=link_to "Posts",posts_path%>

<h3><%=@post.body%></h3>
<p>Created by <%=@post.user.email%></p>
<p>Likes: <%=@post.likes.count%></p>
<%if !current_user.likes.where(post:@post).empty?%>
  <%=form_with url:"/posts/likes/#{@post.id}", method: :delete do |form|%>
    <%=form.submit "Unlike"%>
  <%end%>
<%else%>
  <%=form_with url:"/posts/likes/#{@post.id}" do |form|%>
    <%=form.submit "Like"%>
  <%end%>
<%end%>
<%=form_with model: Comment.new do |form|%>
<%=form.hidden_field :post_id,value:@post.id%>
<%=form.label :body, "Comment"%>
<%=form.text_field :body%>
<%=form.submit "Submit"%>
<%end%>


<ul>
  <%@post.comments.each do |comment|%>
  <li><h4><%=comment.body%></h4><p>Comment by:<%=comment.user.email%></p></li>
  <%end%>
</ul>